/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#ifndef __drake_experimental_lcmt_deformable_tri_meshes_update_hpp__
#define __drake_experimental_lcmt_deformable_tri_meshes_update_hpp__

#include <lcm/lcm_coretypes.h>

#include <vector>
#include "drake/experimental_lcmt_deformable_tri_mesh_update.hpp"

namespace drake
{

/**
 * For each mesh included in this message, provide the number of vertices and
 * their positions in world space at time `timestamp`.
 */
class experimental_lcmt_deformable_tri_meshes_update
{
    public:
        /// in microseconds
        int64_t    timestamp;

        int32_t    num_meshes;

        std::vector< drake::experimental_lcmt_deformable_tri_mesh_update > meshes;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "experimental_lcmt_deformable_tri_meshes_update"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int experimental_lcmt_deformable_tri_meshes_update::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int experimental_lcmt_deformable_tri_meshes_update::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int experimental_lcmt_deformable_tri_meshes_update::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t experimental_lcmt_deformable_tri_meshes_update::getHash()
{
    static int64_t hash = static_cast<int64_t>(_computeHash(NULL));
    return hash;
}

const char* experimental_lcmt_deformable_tri_meshes_update::getTypeName()
{
    return "experimental_lcmt_deformable_tri_meshes_update";
}

int experimental_lcmt_deformable_tri_meshes_update::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->timestamp, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->num_meshes, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->num_meshes; a0++) {
        tlen = this->meshes[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int experimental_lcmt_deformable_tri_meshes_update::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->timestamp, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->num_meshes, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    try {
        this->meshes.resize(this->num_meshes);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->num_meshes; a0++) {
        tlen = this->meshes[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int experimental_lcmt_deformable_tri_meshes_update::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->num_meshes; a0++) {
        enc_size += this->meshes[a0]._getEncodedSizeNoHash();
    }
    return enc_size;
}

uint64_t experimental_lcmt_deformable_tri_meshes_update::_computeHash(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == experimental_lcmt_deformable_tri_meshes_update::getHash)
            return 0;
    const __lcm_hash_ptr cp = { p, experimental_lcmt_deformable_tri_meshes_update::getHash };

    uint64_t hash = 0x0fcd3f1d16b735efLL +
         drake::experimental_lcmt_deformable_tri_mesh_update::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
