/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#ifndef __drake_lcmt_call_python_data_hpp__
#define __drake_lcmt_call_python_data_hpp__

#include <lcm/lcm_coretypes.h>

#include <vector>

namespace drake {

/**
 * Generic data structure to wrap Python data types, for use with CallPython.
 * For historical reasons, interface is modeled on mxArray (see
 * https://www.mathworks.com/help/matlab/matlab_external/matlab-data.html).
 */
class lcmt_call_python_data {
public:
    int8_t data_type;

    int8_t shape_type;

    int32_t rows;

    int32_t cols;

    int32_t num_bytes;

    std::vector<uint8_t> data;

public:
    /// For data_type.
    // If you're using C++11 and are getting compiler errors saying
    // things like ‘constexpr’ needed for in-class initialization of
    // static data member then re-run lcm-gen with '--cpp-std=c++11'
    // to generate code that is compliant with C++11
    static const int8_t REMOTE_VARIABLE_REFERENCE = 0;
    // If you're using C++11 and are getting compiler errors saying
    // things like ‘constexpr’ needed for in-class initialization of
    // static data member then re-run lcm-gen with '--cpp-std=c++11'
    // to generate code that is compliant with C++11
    static const int8_t DOUBLE = 1;
    // If you're using C++11 and are getting compiler errors saying
    // things like ‘constexpr’ needed for in-class initialization of
    // static data member then re-run lcm-gen with '--cpp-std=c++11'
    // to generate code that is compliant with C++11
    static const int8_t CHAR = 2;
    // If you're using C++11 and are getting compiler errors saying
    // things like ‘constexpr’ needed for in-class initialization of
    // static data member then re-run lcm-gen with '--cpp-std=c++11'
    // to generate code that is compliant with C++11
    static const int8_t LOGICAL = 3;
    // If you're using C++11 and are getting compiler errors saying
    // things like ‘constexpr’ needed for in-class initialization of
    // static data member then re-run lcm-gen with '--cpp-std=c++11'
    // to generate code that is compliant with C++11
    static const int8_t INT = 4;
    /// For shape_type.
    // If you're using C++11 and are getting compiler errors saying
    // things like ‘constexpr’ needed for in-class initialization of
    // static data member then re-run lcm-gen with '--cpp-std=c++11'
    // to generate code that is compliant with C++11
    static const int8_t MATRIX = 0;
    // If you're using C++11 and are getting compiler errors saying
    // things like ‘constexpr’ needed for in-class initialization of
    // static data member then re-run lcm-gen with '--cpp-std=c++11'
    // to generate code that is compliant with C++11
    static const int8_t VECTOR = 1;
    // If you're using C++11 and are getting compiler errors saying
    // things like ‘constexpr’ needed for in-class initialization of
    // static data member then re-run lcm-gen with '--cpp-std=c++11'
    // to generate code that is compliant with C++11
    static const int8_t SCALAR = 2;

public:
    /**
     * Encode a message into binary form.
     *
     * @param buf The output buffer.
     * @param offset Encoding starts at thie byte offset into @p buf.
     * @param maxlen Maximum number of bytes to write.  This should generally be
     *  equal to getEncodedSize().
     * @return The number of bytes encoded, or <0 on error.
     */
    inline int encode(void* buf, int offset, int maxlen) const;

    /**
     * Check how many bytes are required to encode this message.
     */
    inline int getEncodedSize() const;

    /**
     * Decode a message from binary form into this instance.
     *
     * @param buf The buffer containing the encoded message.
     * @param offset The byte offset into @p buf where the encoded message starts.
     * @param maxlen The maximum number of bytes to read while decoding.
     * @return The number of bytes decoded, or <0 if an error occured.
     */
    inline int decode(const void* buf, int offset, int maxlen);

    /**
     * Retrieve the 64-bit fingerprint identifying the structure of the message.
     * Note that the fingerprint is the same for all instances of the same
     * message type, and is a fingerprint on the message type definition, not on
     * the message contents.
     */
    inline static int64_t getHash();

    /**
     * Returns "lcmt_call_python_data"
     */
    inline static const char* getTypeName();

    // LCM support functions. Users should not call these
    inline int _encodeNoHash(void* buf, int offset, int maxlen) const;
    inline int _getEncodedSizeNoHash() const;
    inline int _decodeNoHash(const void* buf, int offset, int maxlen);
    inline static uint64_t _computeHash(const __lcm_hash_ptr* p);
};

int lcmt_call_python_data::encode(void* buf, int offset, int maxlen) const {
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (tlen < 0)
        return tlen;
    else
        pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0)
        return tlen;
    else
        pos += tlen;

    return pos;
}

int lcmt_call_python_data::decode(const void* buf, int offset, int maxlen) {
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0)
        return thislen;
    else
        pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0)
        return thislen;
    else
        pos += thislen;

    return pos;
}

int lcmt_call_python_data::getEncodedSize() const {
    return 8 + _getEncodedSizeNoHash();
}

int64_t lcmt_call_python_data::getHash() {
    static int64_t hash = static_cast<int64_t>(_computeHash(NULL));
    return hash;
}

const char* lcmt_call_python_data::getTypeName() {
    return "lcmt_call_python_data";
}

int lcmt_call_python_data::_encodeNoHash(void* buf, int offset, int maxlen) const {
    int pos = 0, tlen;

    tlen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &this->data_type, 1);
    if (tlen < 0)
        return tlen;
    else
        pos += tlen;

    tlen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &this->shape_type, 1);
    if (tlen < 0)
        return tlen;
    else
        pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->rows, 1);
    if (tlen < 0)
        return tlen;
    else
        pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->cols, 1);
    if (tlen < 0)
        return tlen;
    else
        pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->num_bytes, 1);
    if (tlen < 0)
        return tlen;
    else
        pos += tlen;

    if (this->num_bytes > 0) {
        tlen = __byte_encode_array(buf, offset + pos, maxlen - pos, &this->data[0], this->num_bytes);
        if (tlen < 0)
            return tlen;
        else
            pos += tlen;
    }

    return pos;
}

int lcmt_call_python_data::_decodeNoHash(const void* buf, int offset, int maxlen) {
    int pos = 0, tlen;

    tlen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &this->data_type, 1);
    if (tlen < 0)
        return tlen;
    else
        pos += tlen;

    tlen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &this->shape_type, 1);
    if (tlen < 0)
        return tlen;
    else
        pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->rows, 1);
    if (tlen < 0)
        return tlen;
    else
        pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->cols, 1);
    if (tlen < 0)
        return tlen;
    else
        pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->num_bytes, 1);
    if (tlen < 0)
        return tlen;
    else
        pos += tlen;

    if (this->num_bytes) {
        this->data.resize(this->num_bytes);
        tlen = __byte_decode_array(buf, offset + pos, maxlen - pos, &this->data[0], this->num_bytes);
        if (tlen < 0)
            return tlen;
        else
            pos += tlen;
    }

    return pos;
}

int lcmt_call_python_data::_getEncodedSizeNoHash() const {
    int enc_size = 0;
    enc_size += __int8_t_encoded_array_size(NULL, 1);
    enc_size += __int8_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __byte_encoded_array_size(NULL, this->num_bytes);
    return enc_size;
}

uint64_t lcmt_call_python_data::_computeHash(const __lcm_hash_ptr*) {
    uint64_t hash = 0xba5185e6611ca4e8LL;
    return (hash << 1) + ((hash >> 63) & 1);
}

}  // namespace drake

#endif
